---
- name: Deploy JPetStore Application
  hosts: localhost
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      become: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Stop and remove existing container
      docker_container:
        name: jpetstore
        state: absent
      ignore_errors: yes

    - name: Run JPetStore container
      docker_container:
        name: jpetstore
        image: "{{ docker_image }}"
        state: started
        ports:
          - "8080:8080"
        restart_policy: always

    - name: Install Prometheus Node Exporter
      apt:
        name: prometheus-node-exporter
        state: present
      become: yes

    - name: Ensure Prometheus Node Exporter is running
      service:
        name: prometheus-node-exporter
        state: started
        enabled: yes
      become: yes